### ISSUE TITLE
you do not have to put the license in EVERY file (i think)

### ISSUE THREAD

**Issue by ACrazyTown** [despawnedd/AscentViewer#28]
according to 0.12 seconds of looking at the license, it says you have to provide it with the program, aka like a LICENSE.txt file with every release

i don't think you have to put it in EVERY file

**Comment by ACrazyTown** [comment]
also looking at these links:
[1.](https://stackoverflow.com/questions/845895/putting-license-in-each-code-file#:~:text=You%20dont%20need%20it%20for,on%20every%20piece%20of%20text.l)
[2.](https://softwareengineering.stackexchange.com/questions/125836/do-you-have-to-include-a-license-notice-with-every-source-file)

**Comment by despawnedd** [comment]
I've googled it before and it seems that you probably should do that, but I was planning on changing the license to MIT, so it doesn't really matter.

_P. S. - You shouldn't work on your fork until I release a proper commit and revert that one I released a couple of minutes ago. That was pretty much a test_

**Comment by despawnedd** [comment]
I just saw your comment, didn't see it when writing my previous one. It _still_ does not matter that much since the license is gonna be changed anyway

**Comment by despawnedd** [comment]
closing issue

**Comment by ACrazyTown** [comment]
l

**Comment by ACrazyTown** [comment]
i meant k

**Comment by despawnedd** [comment]
you can edit a comment

**Comment by ACrazyTown** [comment]
i know + i dont care + ratio + get better + make a better viewer

**Comment by despawnedd** [comment]
i am so tempted to send that one image butt i won't do it
