### ISSUE TITLE
Viewer broken on macOS

### ISSUE THREAD

**Issue by ACrazyTown** [despawnedd/AscentViewer#6]
Version: **[LEGACY]** 0.1.0.9
Host OS: macOS High Sierra 10.13.6 (17G14042)

Instead of an Image opening normally and taking up all of the window's space it moves and displays text that shouldn't go there.

![image](https://user-images.githubusercontent.com/47027981/103107601-628a1580-4640-11eb-8268-5bf52fd51ff1.png)

**Comment by despawnedd** [comment]
anthony why did you open this issue the version's literally archived

_Sincerely,_
_DespawnedDiamond_

**Comment by ACrazyTown** [comment]
You should atleast patch the Legacy version so it **WORKS**

**Comment by despawnedd** [comment]
it's ***legacy*** but ok, fine

_Sincerely,_
_DespawnedDiamond_

**Comment by ACrazyTown** [comment]
I believe it's related to Line 198 (`imageInfoLabel.config(text = f"{os.path.basename(filePath)}, {imageW}x{imageH}\n{datetime.datetime.fromtimestamp(os.path.getmtime(filePath)).strftime(dateFormat)}\n{imageNumber + 1} out of {len(dirImageList)}")`)

Changing this line makes Tkinter a completely black window, I'll try messing around a bit more and see if I can get it to work.

**Comment by despawnedd** [comment]
Gonna try to mess around it too.

**Comment by ACrazyTown** [comment]
Closing this issue, considering DDIV is Legacy now and the bug doesn't **really** affect the program's functions.

Solution is to just erase/comment out Line 198.
